#!/usr/bin/env python

from pathlib import Path


def parse_ranges(input: str) -> list[int]:
    ranges: list[str] = input.strip().split(',')
    output: list[int] = []
    for r in ranges:
        bounds = r.split('-')
        if len(bounds) == 1:
            output.append(int(bounds[0]))
        else:
            output.extend(list(range(int(bounds[0]), int(bounds[1]) + 1)))
    return output


print("Disabling address space randomization...")
with open("/proc/sys/kernel/randomize_va_space", 'w') as f:
    f.write("0\n")

with open("/sys/devices/system/cpu/isolated", 'r') as f:
    isolcpus: list[int] = parse_ranges(f.read())
print(f"Isolated cpus: {isolcpus}")

smt_pairs: list[tuple[int, ...]] = []
for i in isolcpus:
    path = Path(f"/sys/devices/system/cpu/cpu{i}/topology/thread_siblings_list")
    if not path.is_file(): # because they may already be disabled
        continue
    with open(path, 'r') as f:
        smt_pairs.append(tuple(parse_ranges(f.read())))
for pair in set(smt_pairs):
    for i in pair[1:]:
        print(f"Disabling cpu {i} from SMT pair {pair}...")
        with open(f"/sys/devices/system/cpu/cpu{i}/online", 'w') as f:
            f.write("0\n")
